In [1]:
import numpy as np
import pandas as pd

In [ ]:
#Section 1 -->

In [11]:
#Question 1.1: Convert a Python list x=[[1,2,3],[4,5,6]] into a Numpy array.
x=[[1,2,3],[4,5,6]]
np.array(x)

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
#Question 1.2: Use one line to create a 3x2 2D array with shape of (3,2), filled with 1-6
np.arange(1,7).reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [39]:
#Question 1.3: Use one line to create an array of 2, 4, 6, 8, ..., 98, 100; and find the mean value.
x=np.arange(2,101,2)
print(x)
print('Mean is ',np.mean(x))

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
Mean is  51.0


In [2]:
#Question 1.4: Create an 3x3x3 array filled with arbitrary float numbers; and find the minimum and maximum values.
#x= np.random.random(size=(3,3,3))
#print(x)
#print('Min Value is',np.min(x))
#print('Max Value is',np.max(x))

np.random.random(size=(3,3,3)).min(),np.random.random(size=(3,3,3)).max()

(0.009489598996952897, 0.9605556690695605)

In [35]:
#Question 1.5: Create a 3x4 2D array filled with values from 10 to 21 (included).
np.arange(10,22).reshape(3,4)

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [3]:
#Question 1.6: Create a numpy array of length 10, starting from 5 and has a step of 3 between consecutive numbers.
#np.arange(start=5,stop=35,step=3)
Start=5
Step=3
Length=10
ArrayEnd=(Length*Step)+Start
np.arange(5,ArrayEnd,3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

In [69]:
#Question 1.7: Create a shape (10,10) array with arbitrary values; and find the memory size of this array.
np.random.randint(20,size=(10,10)).itemsize*np.random.randint(20,size=(10,10)).size

400

In [49]:
#Question 1.8: Create a 1-d array of size 10 with arbitrary values but the fifth value should be 5
x=np.random.randint(10,size=10)
x[4]=5
x

array([3, 1, 4, 4, 5, 0, 0, 8, 4, 6])

In [50]:
#Question 1.9: Create an array with values ranging from 10 to 49 (included); and reverse it then (first element becomes last)

np.arange(10,50),np.arange(49,9,-1)

(array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
        27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
        44, 45, 46, 47, 48, 49]),
 array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
        32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
        15, 14, 13, 12, 11, 10]))

In [11]:
#Question 1.10: Create an array of shape (3, 2) with random values from a uniform distribution over [0, 1) and confirm you can get the same value when you run it next time.

np.random.seed(5),np.random.uniform(0,1,size=((3,2)))

(None,
 array([[0.22199317, 0.87073231],
        [0.20671916, 0.91861091],
        [0.48841119, 0.61174386]]))

In [10]:
#Question 1.11: Create a 5x5 matrix with row values ranging from 0 to 4

np.zeros((5,5))+np.arange(5)

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [22]:
#Question 1.12 Add a border (filled with 0's) around an existing array

print(np.ones((5,5)))
np.pad(np.ones((5,5)),pad_width=1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [4]:
#Question 1.13  Create a 5x5 2-d array with values 1,2,3,4,5 on the diagonal (3 points)
x=np.diag(np.array([1,2,3,4,5]),k=0)
print(x)

#Then, make 1,2,3,4 move below the diagonal:
y=np.diag(x)
z=np.diag(y,k=-1)
a,b=np.hsplit(z,[5])
d,e=np.vsplit(a,[5])
print(d)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [13]:
#Question 1.14  Create a 10x10 2-d array with 1 (2 point) on the border and 0 inside (4 points).

x=np.ones((10,10))
print(x)
x[1:-1,1:-1]=0
x

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [7]:
#Question 1.15 Extract the integer part of a random array of positive numbers using 2 different methods, and the result should be an integer array. 

np.random.seed(0)
y=np.random.uniform(0,20,20)
print(y)
x=y.astype(int)
x

[10.97627008 14.30378733 12.05526752 10.89766366  8.47309599 12.91788226
  8.75174423 17.83546002 19.27325521  7.66883038 15.83450076 10.5778984
 11.36089122 18.51193277  1.42072116  1.74258599  0.40436795 16.65239691
 15.56313502 17.40024296]


array([10, 14, 12, 10,  8, 12,  8, 17, 19,  7, 15, 10, 11, 18,  1,  1,  0,
       16, 15, 17])

In [ ]:
#Section 2 -->

In [16]:
#Question 2.1 Find the index of 5th repetition of number 1 in the given array x.

import numpy as np
x=np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
a=np.where(x==1)
b=np.array(a)
print(b[0,4])

8


In [26]:
#Question 2.2 Use np.arange to get an array [1, 2, 3, ..., 9]. Split x into 3 sub-arrays, the length of each sub-array is 4, 2, and 3. 

x=np.arange(1,10)
a=np.split(x,[4,6])
a

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]

In [12]:
#Question 2.3 Use np.arange to generate the 2D array and Use np.split to split the array into left and right halves.

x=np.arange(16).reshape(4,4)
np.abs(np.split(x,2,axis=1))

array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]],

       [[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]])

In [25]:
#Question 2.4 From given 2D array-Slicing to get the sub-array [[10,15], [25,30]] & Getting individual element value "20"

x=np.array([[5,10,15],[20,25,30],[35,40,45]])
a,b=np.hsplit(x,[1])
c,d=np.vsplit(b,[2])
print(c)
p,q,r=np.vsplit(a,[1,2])
print(q)

#print(x[0:2,1:3])


[[10 15]
 [25 30]]
[[20]]


In [87]:
#Question 2.5 Concatenate

x=np.array([[1,2,3],[4,5,6]])
y=np.array([[7,8,9],[10,11,12]])
np.concatenate((x,y),axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [101]:
#Question 2.6 Compute the min/max (min is divided by max) for each row for a given 2d array, in which integer values range from 1 to 10 [1,10) and shape is (5,3).
np.random.seed(9)
x=np.random.randint(1,10,size=(5,3))
x.min(axis=1)/x.max(axis=1)

array([0.66666667, 0.28571429, 0.22222222, 0.22222222, 0.11111111])

In [6]:
#Question 2.7 Normalize a 5x5 random matrix

a=np.random.random((5,5))
print("Before Normalization:")
print(a)
maxi,mini=x.max(),x.min()
b=(x-mini)/(maxi-mini)
print("After Normalization")
print(b)

Before Normalization:
[[0.55094575 0.46108497 0.87526999 0.29568791 0.97372012]
 [0.92823571 0.42277704 0.09512635 0.60761149 0.96137145]
 [0.21831251 0.63924471 0.15897356 0.31477216 0.53820461]
 [0.70653196 0.26460185 0.86827947 0.43971479 0.08850106]
 [0.57526843 0.01649144 0.08678813 0.40029595 0.61456675]]
After Normalization
[[0.10669687 0.57449781 0.11347258 0.96185267 0.2301081 ]
 [1.         0.5312597  0.87552289 0.4441456  0.20917609]
 [0.7680899  0.68397618 0.62844064 0.36910364 0.28563194]
 [0.41334663 0.50363178 0.53982748 0.15885154 0.86114762]
 [0.68466056 0.90168945 0.50510068 0.21900313 0.        ]]


In [117]:
#Question 2.8 Convert 3 arrays into a 1d array

a=np.arange(3)
b=np.arange(3,7)
c=np.arange(7,10)

np.concatenate((a,b,c),axis=0)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
#Question 2.9 Get all items between 15 and 55 from aa, math expression: [15,55]

np.random.seed(0)
x=np.random.randint(0,100,20)
print(x)
for i in range(x.size):
    if(x[i]>=15 and x[i]<=55):
        print (x[i])

[44 47 64 67 67  9 83 21 36 87 70 88 88 12 58 65 39 87 46 88]
44
47
21
36
39
46


In [51]:
#Question 2.10 Get the positions where elements of a and b match.

a=np.array([1,2,3,2,3,4,3,4,5,6])
b=np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

In [134]:
#Question 2.11 Use arange() to create an array from 0 to 20 ( [0,20) ); replace all odd numbers with -1

x=np.arange(0,20)
i=1
for i in x:
    if(i%2!=0):
        x[i]=-1
print(x)

[ 0 -1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14 -1 16 -1 18 -1]


In [7]:
#Question 2.12 Considering a four dimensions array (3,4,3,4) with the values 0-9 randomly, how to get sum over the last two axis at once?

x=np.random.randint(10,size=((3,4,3,4)))
x.sum(axis=3).sum(axis=2)


array([[56, 46, 52, 60],
       [33, 43, 59, 56],
       [62, 36, 51, 52]])